### ISSUE TITLE
Class references throw java.lang.NoClassDefFoundError when not referenced in main mod file

### ISSUE THREAD

**Issue by xrnss** [cookiedragon234/falcon-forge#10]
okay so i actually did everything and got it built and it loads the client.jar thing (i had to disable the security checks because for whatever reason the disable java agent thing crashes it every time even tho there is no agent) 

but for whatever reason, it thinks one of my classes is null even though it exists i'll like try to explain

com.thing.mod-->
       mod.java
       Utils.java
       someModule.java
       ... other stuff

so basically inside Utils we have something like 
```
public class Utils {
    public static Minecraft minecraft = Minecraft.getMinecraft();
    public static Mod mod = mod.getInstance();
    public static ConfigHandler config;
    // other stuff
}
```

and then inside mod we have your stereotypical mod, with 2 functions isThingEnabled and also isOtherThingEnabled 

but the error seems to originate in someModule.java

```
@SubscribeEvent
public void onTick(TickEvent event) {
     Minecraft mc = Utils.minecraft; // works fine probably
     if (Utils.mod.isThingEnabled() && Utils.mod.isOtherThingEnabled()) // throws a null pointer exception
```

this is confusing because like it works without this falcon thing and idk if im missing something but yeah
lmk if i need to provide anymore details or anything sorry if this makes no sense

edit: onTick is running perfectly fine on the stack trace like its getting fired every tick i just dont get why either mod or mod.isThingEnabled is undefined do i have to define it in the FalconMod.kt file ??

**Comment by x4e** [comment]
Have you renamed any instances of `com/myclient` to `com/thing/mod`?
https://github.com/x4e/falcon-forge/search?q=myclient

**Comment by xrnss** [comment]
Sorry for the late response but yes, I searched everywhere and I got nothing

**Comment by x4e** [comment]
I'm sorry but then I am not sure. You will have to work this out yourself.

**Comment by xrnss** [comment]
ill see if i can find out any more information

**Comment by xrnss** [comment]
alright, i found the issue. basically if you have a class that you do not reference in your main mod file in client.jar, any time you try and reference it in another file it will cause a java.lang.NoClassDefFoundError error, even though upon adding additional logging to the Loader.kt file, you can see that the class is indeed being loaded into the resourceCache and it is being correctly set. is there a way i can like make all classes referenced and shit if yk what i mean like on loading

**Comment by xrnss** [comment]
Additionally, if you reference LoadedModMainFile.instance even if the mod has the @Mod annotation, it will be null, due to the fact that mod is not registered but just kind of an extension from the one from loader.jar To anyone reading this, make sure you remove the @Mod annotation and treat that file like a regular class, not a mod! It will save many hours of messing around and trying to find issues, unless I am just stupid haha

**Comment by xrnss** [comment]
I have also managed to work around the issue I brought up 2 comments ago by adding a new instance of every class in my project, in the preinit function in FalconMod.kt, like this:

```
        @Mod.EventHandler
	fun preinit(event: FMLPreInitializationEvent) {
		clientMod.preinit(event)
		someClass();
                anotherClass();
	}
```

**Comment by xrnss** [comment]
See #14
