### ISSUE TITLE
Could not find net.minecraftforge:forgeBin:1.12.2-14.23.5.2847.

### ISSUE THREAD

**Issue by XeonLyfe** [cookiedragon234/falcon-forge#12]
When ever I try to build falcon I get this error.

Could not find net.minecraftforge:forgeBin:1.12.2-14.23.5.2847.
Searched in the following locations:
  - https://maven.minecraftforge.net/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.pom
  - https://maven.minecraftforge.net/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.jar
  - https://repo.maven.apache.org/maven2/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.pom
  - https://repo.maven.apache.org/maven2/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.jar
  - https://libraries.minecraft.net/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.pom
  - https://libraries.minecraft.net/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.jar
  - https://repo.spongepowered.org/repository/maven-public/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.pom
  - https://repo.spongepowered.org/repository/maven-public/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.jar
  - https://jitpack.io/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.pom
  - https://jitpack.io/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.jar
  - https://repo.maven.apache.org/maven2/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.pom
  - https://repo.maven.apache.org/maven2/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.jar
  - file:/C:/Users/XeonLyfeGPC/.gradle/caches/minecraft/deobfedDeps/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.pom
  - file:/C:/Users/XeonLyfeGPC/.gradle/caches/minecraft/deobfedDeps/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.jar
  - file:/C:/Users/XeonLyfeGPC/.gradle/caches/minecraft/net/minecraftforge/forge/1.12.2-14.23.5.2847/stable/39/forgeBin-1.12.2-14.23.5.2847.jar
  - file:/C:/Users/XeonLyfeGPC/.gradle/caches/minecraft/net/minecraftforge/forge/1.12.2-14.23.5.2847/stable/39/forgeBin.jar
Required by:
    project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

I'm not that good at coding/diagnostics so I don't know what to do.
I would also like a better explanation on how to use falcon forge. 

Thanks,
XeonLyfe

**Comment by xrnss** [comment]
this isn't a falcon issue - it's to do with the like minecraft forge cdn shit 
you'll find the right maven repo to use somewhere im pretty sure this is outdated
