### ISSUE TITLE
Obfuscation

### ISSUE THREAD

**Issue by xrnss** [cookiedragon234/falcon-forge#13]
How would I go about obfuscating this considering it's in separate jars? I've tried using binscure but even on the loader jar it just crashes even if I only turn on one setting. Any help appreciated

**Comment by x4e** [comment]
This is a problem specific to the obfuscator you are using, not falcon.

**Comment by xrnss** [comment]
I request this be reopened but ignore the part about binscure for general advice on obfuscation across the JARs

**Comment by xrnss** [comment]
i
