### ISSUE TITLE
credit

### ISSUE THREAD

**Issue by phobologicalt** [cookiedragon234/falcon-forge#6]
If I use this for my private do I need to supply credit?

**Comment by x4e** [comment]
I am not a lawyer so I can not answer this for you. I recommend you consult the license (https://github.com/x4e/falcon-forge/blob/master/LICENSE) and if need be consult a lawyer.

**Comment by x4e** [comment]
I think you may find this paragraph particularly important:

>   For example, if you distribute copies of such a program, whether
> gratis or for a fee, you must give the recipients all the rights that
> you have.  You must make sure that they, too, receive or can get the
> source code.  And you must show them these terms so they know their
> rights.

**Comment by x4e** [comment]
I would also add that whether or not you *need* to supply credit, I always appreciate credit for my work :)
