### ISSUE TITLE
cannot accest class  and type mismatch

### ISSUE THREAD

**Issue by goztb22** [cookiedragon234/falcon-forge#8]
\build\sources\main\kotlin\dev\binclub\falcon\FalconMod.kt: (40, 10): Cannot access class 'FMLPostInitializationEvent'. Check your module classpath for missing or conflicting dependencies

build\sources\main\kotlin\dev\binclub\falcon\FalconMod.kt: (40, 19): Type mismatch: inferred type is net.minecraftforge.fml.common.event.FMLPostInitializationEvent but FMLPostInitializationEven

ok

**Comment by x4e** [comment]
This is not an issue with falcon
